baseURL = 'https://postfiatorg.github.io'
languageCode = 'en-us'
title = 'goodalexander'
theme = 'PaperMod'

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
# googleAnalytics = "UA-123-45"

[minify]
disableXML = true
# minifyOutput = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.taxonomies]
      category = "categories"
      tag = "tags"
      series = "series"
    [[languages.en.menu.main]]
      name = "Tags"
      url = "tags/"
      weight = 10
    [[languages.en.menu.main]]
      name = "Positions"
      url = "positions/"
      weight = 20
    [[languages.en.menu.main]]
      name = "Search"
      url = "search/"
      weight = 30
    [[languages.en.menu.main]]
      name = "Archive"
      url = "archives"
      weight = 40
    [[languages.en.menu.main]]
      name = "Twitter"
      url = "https://www.twitter.com/goodalexander"
      weight = 50
      
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  description = "Good PaperMod"
  author = "goodalexander"
  # author = ["Me", "You"]
  defaultTheme = "auto"
  # disableThemeToggle = true
  ShowShareButtons = true
  ShowReadingTime = true
  # disableSpecial1stPost = true
  displayFullLangName = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  # comments = false
  images = ["papermod-cover.png"]
  [markup.goldmark.renderer]
    unsafe = true


[params.homeInfoParams]
  Title = "goodalexander"
  Content = '''
  welcome to goodalexander 
  
  - **goodalexander** posts from 2022 & 2023 explore the digital dystopia we live in and in 2024 focus exclusively on crypto/ trading content.   
  
  - You can also [Subscribe via Email on Ghost](https://goodalexander.ghost.io/#/portal/).'''
  
  [[params.socialIcons]]
    name = "twitter"
    title = "Follow me on twitter"
    url = "https://www.twitter.com/goodalexander"
  
  [[params.socialIcons]]
    name = "Discord"
    title = "Join discord community"
    url = "https://discord.gg/Kzu8ezhY"
  
  [[params.socialIcons]]
    name = "github"
    title = "My Github"
    url = "https://www.github.com/goodalexander"

#  [params.editPost]
#    URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
#    Text = "Suggest Changes"
#    appendFilePath = true

  # [params.label]
  #   text = "Home"
  #   icon = "icon.png"
  #   iconHeight = 35

  # [params.analytics]
  #   [params.analytics.google]
  #     SiteVerificationTag = "XYZabc"

  [params.assets]
    disableHLJS = true
